
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATRIBUIR DERIVAR EQUALS ID INTEGRAR LPAREN MOSTRAR NUMBER OP RPARENcomando : ATRIBUIR ID EQUALS expressaocomando : MOSTRAR expressaocomando : DERIVAR expressaocomando : INTEGRAR expressaoexpressao : expressao OP termoexpressao : termotermo : IDtermo : NUMBERtermo : LPAREN expressao RPAREN'
    
_lr_action_items = {'ATRIBUIR':([0,],[2,]),'MOSTRAR':([0,],[3,]),'DERIVAR':([0,],[4,]),'INTEGRAR':([0,],[5,]),'$end':([1,7,8,9,10,12,13,17,18,19,],[0,-2,-6,-7,-8,-3,-4,-1,-5,-9,]),'ID':([2,3,4,5,11,14,15,],[6,9,9,9,9,9,9,]),'NUMBER':([3,4,5,11,14,15,],[10,10,10,10,10,10,]),'LPAREN':([3,4,5,11,14,15,],[11,11,11,11,11,11,]),'EQUALS':([6,],[14,]),'OP':([7,8,9,10,12,13,16,17,18,19,],[15,-6,-7,-8,15,15,15,15,-5,-9,]),'RPAREN':([8,9,10,16,18,19,],[-6,-7,-8,19,-5,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),'expressao':([3,4,5,11,14,],[7,12,13,16,17,]),'termo':([3,4,5,11,14,15,],[8,8,8,8,8,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> ATRIBUIR ID EQUALS expressao','comando',4,'p_comando_atribuir','main.py',54),
  ('comando -> MOSTRAR expressao','comando',2,'p_comando_mostrar','main.py',58),
  ('comando -> DERIVAR expressao','comando',2,'p_comando_derivar','main.py',62),
  ('comando -> INTEGRAR expressao','comando',2,'p_comando_integrar','main.py',66),
  ('expressao -> expressao OP termo','expressao',3,'p_expressao_operacao','main.py',70),
  ('expressao -> termo','expressao',1,'p_expressao_termo','main.py',74),
  ('termo -> ID','termo',1,'p_termo_id','main.py',78),
  ('termo -> NUMBER','termo',1,'p_termo_number','main.py',82),
  ('termo -> LPAREN expressao RPAREN','termo',3,'p_termo_parenteses','main.py',86),
]
