
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATRIBUIR DERIVAR EQUALS ID INTEGRAR LPAREN MOSTRAR NUMBER OP RPARENcomando : ATRIBUIR ID EQUALS expressaocomando : MOSTRAR expressaocomando : DERIVAR expressaocomando : INTEGRAR expressaoexpressao : expressao OP termoexpressao : termotermo : IDtermo : NUMBERtermo : LPAREN expressao RPARENcomando : expressao'
    
_lr_action_items = {'ATRIBUIR':([0,],[2,]),'MOSTRAR':([0,],[5,]),'DERIVAR':([0,],[6,]),'INTEGRAR':([0,],[7,]),'ID':([0,2,5,6,7,10,12,17,],[3,11,3,3,3,3,3,3,]),'NUMBER':([0,5,6,7,10,12,17,],[9,9,9,9,9,9,9,]),'LPAREN':([0,5,6,7,10,12,17,],[10,10,10,10,10,10,10,]),'$end':([1,3,4,8,9,13,14,15,18,19,20,],[0,-7,-10,-6,-8,-2,-3,-4,-5,-9,-1,]),'OP':([3,4,8,9,13,14,15,16,18,19,20,],[-7,12,-6,-8,12,12,12,12,-5,-9,12,]),'RPAREN':([3,8,9,16,18,19,],[-7,-6,-8,19,-5,-9,]),'EQUALS':([11,],[17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),'expressao':([0,5,6,7,10,17,],[4,13,14,15,16,20,]),'termo':([0,5,6,7,10,12,17,],[8,8,8,8,8,18,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> ATRIBUIR ID EQUALS expressao','comando',4,'p_comando_atribuir','main.py',55),
  ('comando -> MOSTRAR expressao','comando',2,'p_comando_mostrar','main.py',59),
  ('comando -> DERIVAR expressao','comando',2,'p_comando_derivar','main.py',63),
  ('comando -> INTEGRAR expressao','comando',2,'p_comando_integrar','main.py',67),
  ('expressao -> expressao OP termo','expressao',3,'p_expressao_operacao','main.py',71),
  ('expressao -> termo','expressao',1,'p_expressao_termo','main.py',75),
  ('termo -> ID','termo',1,'p_termo_id','main.py',79),
  ('termo -> NUMBER','termo',1,'p_termo_number','main.py',83),
  ('termo -> LPAREN expressao RPAREN','termo',3,'p_termo_parenteses','main.py',87),
  ('comando -> expressao','comando',1,'p_comando_expressao','main.py',91),
]
